[phases.setup]
# Install Node.js 22 + build dependencies for native modules
nixPkgs = [
  "nodejs_22",
  "python3",
  "gnumake",
  "gcc",
  "pkg-config",
  "libsodium",
  "libopus"
]

[phases.install]
cmds = ["npm ci"]

[start]
cmd = "npm start"
